version: '3'

services: 
    db:
        image: postgres:latest
        container_name: my-db
        ports: 
            - 54321:5432
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        ports: 
            - 4433:443
            - 8080:80
        environment: 
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    myapp:
        image: phatthakan/myapp:fixsharp
        container_name: myapp
        ports: 
           - 1337:1337
        environment: 
           - DATABASE_CLIENT=${DATABASE_CLIENT}
           - DATABASE_HOST=${DATABASE_HOST}
           - DATABASE_PORT=${DATABASE_PORT}
           - DATABASE_NAME=${DATABASE_NAME}
           - DATABASE_USERNAME=${DATABASE_USERNAME}
           - DATABASE_PASSWORD=${DATABASE_PASSWORD}
           - DATABASE_SSL=${DATABASE_SSL}
